# Install try-runtime
name: Install try-runtime

runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Rust Setup
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        components: rustfmt, clippy

    - name: Install try-runtime
      run: cargo install --git https://github.com/paritytech/try-runtime-cli --locked
      shell: bash