[settings]
timeout = 1000

[relaychain]
default_command = "../bin/polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2000
cumulus_based = true 

  [parachains.collator]
  name = "collator-2000-01"
  command = "./target/release/parachain-template-node"
  rpc_port = 9933
